<Project Sdk="Microsoft.NET.Sdk.Worker">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <RootNamespace>TapirSLMP.E2E.SealerHost</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" />
    <ProjectReference Include="../../../../src/TapirSLMP.Sealer/TapirSLMP.Sealer.csproj" />
    <ProjectReference Include="../../../../src/TapirSLMP.Client/TapirSLMP.Client.csproj" />
  </ItemGroup>
</Project>
